import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link"; // SPA para cargar solo lo necesario (sin refresacar) */
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Alpha BCZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Teko:wght@300&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar />

      {/*  <main className={styles.main}>
        <section className={styles.title}>
          <Link href="/">
            <h1 className="text-3xl font-bold underline">ALPHA BCZ</h1>
          </Link>
        </section>

        <section>
          {" "}
          <Link href="/gallery">
            <a>GALLERY</a>
          </Link>
        </section>
      </main> */}
    </div>
  );
}
